package com.lms.model;

public class ConsultantMaster {

	private String CONSULATNT_NAME;
	private String CONSULATNT_CONTACT_PERSON; 
	private String CONSULATNT_CONTACT_MOBILE; 
	private String CONSULATNT_EMAIL; 
	private String CONSULATNT_ALTERNATE_MOBILE; 
	private String CREATED_BY; 
	private String CRETAED_DATE;
	public String getCONSULATNT_NAME() {
		return CONSULATNT_NAME;
	}
	public void setCONSULATNT_NAME(String cONSULATNT_NAME) {
		CONSULATNT_NAME = cONSULATNT_NAME;
	}
	public String getCONSULATNT_CONTACT_PERSON() {
		return CONSULATNT_CONTACT_PERSON;
	}
	public void setCONSULATNT_CONTACT_PERSON(String cONSULATNT_CONTACT_PERSON) {
		CONSULATNT_CONTACT_PERSON = cONSULATNT_CONTACT_PERSON;
	}
	public String getCONSULATNT_CONTACT_MOBILE() {
		return CONSULATNT_CONTACT_MOBILE;
	}
	public void setCONSULATNT_CONTACT_MOBILE(String cONSULATNT_CONTACT_MOBILE) {
		CONSULATNT_CONTACT_MOBILE = cONSULATNT_CONTACT_MOBILE;
	}
	public String getCONSULATNT_EMAIL() {
		return CONSULATNT_EMAIL;
	}
	public void setCONSULATNT_EMAIL(String cONSULATNT_EMAIL) {
		CONSULATNT_EMAIL = cONSULATNT_EMAIL;
	}
	public String getCONSULATNT_ALTERNATE_MOBILE() {
		return CONSULATNT_ALTERNATE_MOBILE;
	}
	public void setCONSULATNT_ALTERNATE_MOBILE(String cONSULATNT_ALTERNATE_MOBILE) {
		CONSULATNT_ALTERNATE_MOBILE = cONSULATNT_ALTERNATE_MOBILE;
	}
	public String getCREATED_BY() {
		return CREATED_BY;
	}
	public void setCREATED_BY(String cREATED_BY) {
		CREATED_BY = cREATED_BY;
	}
	public String getCRETAED_DATE() {
		return CRETAED_DATE;
	}
	public void setCRETAED_DATE(String cRETAED_DATE) {
		CRETAED_DATE = cRETAED_DATE;
	}
	@Override
	public String toString() {
		return "ConsultantMaster [CONSULATNT_NAME=" + CONSULATNT_NAME
				+ ", CONSULATNT_CONTACT_PERSON=" + CONSULATNT_CONTACT_PERSON
				+ ", CONSULATNT_CONTACT_MOBILE=" + CONSULATNT_CONTACT_MOBILE
				+ ", CONSULATNT_EMAIL=" + CONSULATNT_EMAIL
				+ ", CONSULATNT_ALTERNATE_MOBILE="
				+ CONSULATNT_ALTERNATE_MOBILE + ", CREATED_BY=" + CREATED_BY
				+ ", CRETAED_DATE=" + CRETAED_DATE + "]";
	}
}
