package com.lms.model;

public class Quoted_Projects
{
	private int DTL_ID;
	private String LEAD_ID;
	private String TRANSACTION_TYPE;
	private String PROJECT_TYPE;
	private String ENQUIRY_TYPE;
	private String LEAD_BUDG;
	private String PROJECT_EXE_PLACE;
	private String PROJECT_EXE_STATE;
	private String LEAD_CREATION_PLACE;
	private String LEAD_CREATION_STATE;
	private String LEAD_CRETION_SHORT_STATE;
	private String LEAD_CREATION_REGION;
	private String CREATION_DATE;
	private String CREATED_BY;
	private String MODIFIED_DATE;
	private String MODIFIED_BY;
	private String OWNER_ID;
	private String OWNER_NAME;
	private String COMMENTS;	
	private String DG_TYPE;
	private String SEGMENT;
	private String COMPETITIONS;
	private String LEAD_CHANCES;
	private String LEAD_STATUS;
	private String CONSULTANT_NAME;
	private String CONSULTANT_PERSON_NAME;
	private String CONSULTANT_MOBILE_NO;
	private String CUSTOMER_NAME;
	private String CUSTOMER_EMAIL_ADDRESS;
	private String CUSTOMER_ADDRESS;
	private String CUSTOMER_MOBILENO;
	private String CUSTOMER_ALTERNATE_NO;
	private String END_PERSON_CUSTOMER_NAME;
	private String END_PERSON_CUSTOMER_CONTACTNO;
	private String PMC_NAME;
	private String PMC_CONTACT_PERSON;
	private String PMC_CONTACT_NO;
	private String PMC_CONTACT_ALT_NO;
	private String LOW_SIDE_SUPPLY_BASIC;
	private String LOW_SIDE_LABOUR_BASIC;
	private String LOW_SIDE_MARGIN;
	private String PROJECT_MARGIN;
	private String DG_ED_VALUE;
	private String PROJECT_TOTAL;
	private String DTL_RATING;
	private String DTL_ITEM_TYPE;
	private String DTL_ENGINE_MAKE;
	private String DTL_ENGINE_MODEL;
	private String DTL_ALTERNATOR_MAKE;
	private String DTL_ALTERNATOR_MODEL;
	private String DTL_VOLTAGE;
	private String DTL_HZ;
	private String DTL_QTY;
	private String DTL_COOLING_SYSTEM;
	private String DTL_AMOUNT;
	private String DTL_FLEX1;
	private String PROJECT_REFERENCE;
	
	
	public Quoted_Projects()
	{
		
	}
	
	public Quoted_Projects(String LEAD_ID,String TRANSACTION_TYPE,String PROJECT_TYPE,String ENQUIRY_TYPE,String LEAD_BUDG,String PROJECT_EXE_PLACE,String PROJECT_EXE_STATE,String LEAD_CREATION_PLACE,String LEAD_CREATION_STATE,String LEAD_CRETION_SHORT_STATE,String LEAD_CREATION_REGION,String CREATION_DATE,String CREATED_BY,String MODIFIED_DATE,String MODIFIED_BY,String OWNER_ID,String OWNER_NAME,String DG_TYPE,String SEGMENT,String COMPETITIONS,String LEAD_CHANCES,String LEAD_STATUS,String CONSULTANT_NAME,String CONSULTANT_PERSON_NAME,String CONSULTANT_MOBILE_NO,String CUSTOMER_NAME,String CUSTOMER_EMAIL_ADDRESS,String CUSTOMER_ADDRESS,String CUSTOMER_MOBILENO,String CUSTOMER_ALTERNATE_NO,String END_PERSON_CUSTOMER_NAME,String END_PERSON_CUSTOMER_CONTACTNO,String PMC_NAME,String PMC_CONTACT_PERSON,String PMC_CONTACT_NO,String PMC_CONTACT_ALT_NO,String LOW_SIDE_SUPPLY_BASIC,String LOW_SIDE_LABOUR_BASIC,String LOW_SIDE_MARGIN,String PROJECT_MARGIN,String DG_ED_VALUE,String PROJECT_TOTAL,String DTL_RATING,String DTL_ITEM_TYPE,String DTL_ENGINE_MAKE,String DTL_ENGINE_MODEL,String DTL_ALTERNATOR_MAKE,String DTL_ALTERNATOR_MODEL,String DTL_VOLTAGE,String DTL_HZ,String DTL_QTY,String DTL_COOLING_SYSTEM,String DTL_AMOUNT,String DTL_FLEX1,String PROJECT_REFERENCE, int DTL_ID,String COMMENTS)
	{
		this.LEAD_ID=LEAD_ID;
		this.TRANSACTION_TYPE=TRANSACTION_TYPE;
		this.PROJECT_TYPE=PROJECT_TYPE;
		this.ENQUIRY_TYPE=ENQUIRY_TYPE;
		this.LEAD_BUDG=LEAD_BUDG;
		this.PROJECT_EXE_PLACE=PROJECT_EXE_PLACE;
		this.PROJECT_EXE_STATE=PROJECT_EXE_STATE;
		this.LEAD_CREATION_PLACE=LEAD_CREATION_PLACE;
		this.LEAD_CREATION_STATE=LEAD_CREATION_STATE;
		this.LEAD_CRETION_SHORT_STATE=LEAD_CRETION_SHORT_STATE;
		this.LEAD_CREATION_REGION=LEAD_CREATION_REGION;
		this.CREATION_DATE=CREATION_DATE;
		this.CREATED_BY=CREATED_BY;
		this.MODIFIED_DATE=MODIFIED_DATE;
		this.MODIFIED_BY=MODIFIED_BY;
		this.OWNER_ID=OWNER_ID;
		this.OWNER_NAME=OWNER_NAME;
		this.COMMENTS=COMMENTS;
		this.DG_TYPE=DG_TYPE;
		this.SEGMENT=SEGMENT;
		this.COMPETITIONS=COMPETITIONS;
		this.LEAD_CHANCES=LEAD_CHANCES;
		this.LEAD_STATUS=LEAD_STATUS;
		this.CONSULTANT_NAME=CONSULTANT_NAME;
		this.CONSULTANT_PERSON_NAME=CONSULTANT_PERSON_NAME;
		this.CONSULTANT_MOBILE_NO=CONSULTANT_MOBILE_NO;
		this.CUSTOMER_NAME=CUSTOMER_NAME;
		this.CUSTOMER_EMAIL_ADDRESS=CUSTOMER_EMAIL_ADDRESS;
		this.CUSTOMER_ADDRESS=CUSTOMER_ADDRESS;
		this.CUSTOMER_MOBILENO=CUSTOMER_MOBILENO;
		this.CUSTOMER_ALTERNATE_NO=CUSTOMER_ALTERNATE_NO;
		this.END_PERSON_CUSTOMER_NAME=END_PERSON_CUSTOMER_NAME;
		this.END_PERSON_CUSTOMER_CONTACTNO=END_PERSON_CUSTOMER_CONTACTNO;
		this.PMC_NAME=PMC_NAME;
		this.PMC_CONTACT_PERSON=PMC_CONTACT_PERSON;
		this.PMC_CONTACT_NO=PMC_CONTACT_NO;
		this.PMC_CONTACT_ALT_NO=PMC_CONTACT_ALT_NO;
		this.LOW_SIDE_SUPPLY_BASIC=LOW_SIDE_SUPPLY_BASIC;
		this.LOW_SIDE_LABOUR_BASIC=LOW_SIDE_LABOUR_BASIC;
		this.LOW_SIDE_MARGIN=LOW_SIDE_MARGIN;
		this.PROJECT_MARGIN=PROJECT_MARGIN;
		this.DG_ED_VALUE=DG_ED_VALUE;
		this.PROJECT_TOTAL=PROJECT_TOTAL;
		this.DTL_RATING=DTL_RATING;
		this.DTL_ITEM_TYPE=DTL_ITEM_TYPE;
		this.DTL_ENGINE_MAKE=DTL_ENGINE_MAKE;
		this.DTL_ENGINE_MODEL=DTL_ENGINE_MODEL;
		this.DTL_ALTERNATOR_MAKE=DTL_ALTERNATOR_MAKE;
		this.DTL_ALTERNATOR_MODEL=DTL_ALTERNATOR_MODEL;
		this.DTL_VOLTAGE=DTL_VOLTAGE;
		this.DTL_HZ=DTL_HZ;
		this.DTL_QTY=DTL_QTY;
		this.DTL_COOLING_SYSTEM=DTL_COOLING_SYSTEM;
		this.DTL_AMOUNT=DTL_AMOUNT;
		this.DTL_FLEX1=DTL_FLEX1;
		this.PROJECT_REFERENCE=PROJECT_REFERENCE;
		this.DTL_ID=DTL_ID;

	}
	
	public Quoted_Projects(String LEAD_ID, String DTL_ENGINE_MAKE, String DTL_ALTERNATOR_MODEL, String PROJECT_TYPE, String LEAD_STATUS, String LEAD_CHANCES, int DTL_ID)
	{
		this.DTL_ENGINE_MAKE=DTL_ENGINE_MAKE;
		this.DTL_ALTERNATOR_MODEL=DTL_ALTERNATOR_MODEL;
		this.PROJECT_TYPE=PROJECT_TYPE;
		this.DTL_ID=DTL_ID;
		this.LEAD_STATUS=LEAD_STATUS;
		this.LEAD_CHANCES=LEAD_CHANCES;
	}
	
	public int getDTL_ID() {
		return DTL_ID;
	}
	public void setDTL_ID(int dTL_ID) {
		DTL_ID = dTL_ID;
	}
	public String getLEAD_ID() {
		return LEAD_ID;
	}
	public void setLEAD_ID(String lEAD_ID) {
		LEAD_ID = lEAD_ID;
	}
	public String getTRANSACTION_TYPE() {
		return TRANSACTION_TYPE;
	}
	public void setTRANSACTION_TYPE(String tRANSACTION_TYPE) {
		TRANSACTION_TYPE = tRANSACTION_TYPE;
	}
	public String getPROJECT_TYPE() {
		return PROJECT_TYPE;
	}
	public void setPROJECT_TYPE(String pROJECT_TYPE) {
		PROJECT_TYPE = pROJECT_TYPE;
	}
	public String getENQUIRY_TYPE() {
		return ENQUIRY_TYPE;
	}
	public void setENQUIRY_TYPE(String eNQUIRY_TYPE) {
		ENQUIRY_TYPE = eNQUIRY_TYPE;
	}
	public String getLEAD_BUDG() {
		return LEAD_BUDG;
	}
	public String getPROJECT_EXE_PLACE() {
		return PROJECT_EXE_PLACE;
	}
	public void setPROJECT_EXE_PLACE(String pROJECT_EXE_PLACE) {
		PROJECT_EXE_PLACE = pROJECT_EXE_PLACE;
	}
	public void setLEAD_BUDG(String lEAD_BUDG) {
		LEAD_BUDG = lEAD_BUDG;
	}
	public String getPROJECT_EXE_STATE() {
		return PROJECT_EXE_STATE;
	}
	public void setPROJECT_EXE_STATE(String pROJECT_EXE_STATE) {
		PROJECT_EXE_STATE = pROJECT_EXE_STATE;
	}
	public String getLEAD_CREATION_PLACE() {
		return LEAD_CREATION_PLACE;
	}
	public void setLEAD_CREATION_PLACE(String lEAD_CREATION_PLACE) {
		LEAD_CREATION_PLACE = lEAD_CREATION_PLACE;
	}
	public String getLEAD_CREATION_STATE() {
		return LEAD_CREATION_STATE;
	}
	public void setLEAD_CREATION_STATE(String lEAD_CREATION_STATE) {
		LEAD_CREATION_STATE = lEAD_CREATION_STATE;
	}
	public String getLEAD_CRETION_SHORT_STATE() {
		return LEAD_CRETION_SHORT_STATE;
	}
	public void setLEAD_CRETION_SHORT_STATE(String lEAD_CRETION_SHORT_STATE) {
		LEAD_CRETION_SHORT_STATE = lEAD_CRETION_SHORT_STATE;
	}
	public String getLEAD_CREATION_REGION() {
		return LEAD_CREATION_REGION;
	}
	public void setLEAD_CREATION_REGION(String lEAD_CREATION_REGION) {
		LEAD_CREATION_REGION = lEAD_CREATION_REGION;
	}
	public String getCREATION_DATE() {
		return CREATION_DATE;
	}
	public void setCREATION_DATE(String cREATION_DATE) {
		CREATION_DATE = cREATION_DATE;
	}
	public String getCREATED_BY() {
		return CREATED_BY;
	}
	public void setCREATED_BY(String cREATED_BY) {
		CREATED_BY = cREATED_BY;
	}
	public String getMODIFIED_DATE() {
		return MODIFIED_DATE;
	}
	public void setMODIFIED_DATE(String mODIFIED_DATE) {
		MODIFIED_DATE = mODIFIED_DATE;
	}
	public String getMODIFIED_BY() {
		return MODIFIED_BY;
	}
	public void setMODIFIED_BY(String mODIFIED_BY) {
		MODIFIED_BY = mODIFIED_BY;
	}
	public String getOWNER_ID() {
		return OWNER_ID;
	}
	public void setOWNER_ID(String oWNER_ID) {
		OWNER_ID = oWNER_ID;
	}
	public String getOWNER_NAME() {
		return OWNER_NAME;
	}
	public void setOWNER_NAME(String oWNER_NAME) {
		OWNER_NAME = oWNER_NAME;
	}
	public String getCOMMENTS() {
		return COMMENTS;
	}

	public void setCOMMENTS(String cOMMENTS) {
		COMMENTS = cOMMENTS;
	}

	public String getDG_TYPE() {
		return DG_TYPE;
	}
	public void setDG_TYPE(String dG_TYPE) {
		DG_TYPE = dG_TYPE;
	}
	public String getSEGMENT() {
		return SEGMENT;
	}
	public void setSEGMENT(String sEGMENT) {
		SEGMENT = sEGMENT;
	}
	public String getCOMPETITIONS() {
		return COMPETITIONS;
	}
	public void setCOMPETITIONS(String cOMPETITIONS) {
		COMPETITIONS = cOMPETITIONS;
	}
	public String getLEAD_CHANCES() {
		return LEAD_CHANCES;
	}
	public void setLEAD_CHANCES(String lEAD_CHANCES) {
		LEAD_CHANCES = lEAD_CHANCES;
	}
	public String getLEAD_STATUS() {
		return LEAD_STATUS;
	}
	public void setLEAD_STATUS(String lEAD_STATUS) {
		LEAD_STATUS = lEAD_STATUS;
	}
	public String getCONSULTANT_NAME() {
		return CONSULTANT_NAME;
	}
	public void setCONSULTANT_NAME(String cONSULTANT_NAME) {
		CONSULTANT_NAME = cONSULTANT_NAME;
	}
	public String getCONSULTANT_PERSON_NAME() {
		return CONSULTANT_PERSON_NAME;
	}
	public void setCONSULTANT_PERSON_NAME(String cONSULTANT_PERSON_NAME) {
		CONSULTANT_PERSON_NAME = cONSULTANT_PERSON_NAME;
	}
	public String getCONSULTANT_MOBILE_NO() {
		return CONSULTANT_MOBILE_NO;
	}
	public void setCONSULTANT_MOBILE_NO(String cONSULTANT_MOBILE_NO) {
		CONSULTANT_MOBILE_NO = cONSULTANT_MOBILE_NO;
	}
	public String getCUSTOMER_NAME() {
		return CUSTOMER_NAME;
	}
	public void setCUSTOMER_NAME(String cUSTOMER_NAME) {
		CUSTOMER_NAME = cUSTOMER_NAME;
	}
	public String getCUSTOMER_EMAIL_ADDRESS() {
		return CUSTOMER_EMAIL_ADDRESS;
	}
	public void setCUSTOMER_EMAIL_ADDRESS(String cUSTOMER_EMAIL_ADDRESS) {
		CUSTOMER_EMAIL_ADDRESS = cUSTOMER_EMAIL_ADDRESS;
	}
	public String getCUSTOMER_ADDRESS() {
		return CUSTOMER_ADDRESS;
	}
	public void setCUSTOMER_ADDRESS(String cUSTOMER_ADDRESS) {
		CUSTOMER_ADDRESS = cUSTOMER_ADDRESS;
	}
	public String getCUSTOMER_MOBILENO() {
		return CUSTOMER_MOBILENO;
	}
	public void setCUSTOMER_MOBILENO(String cUSTOMER_MOBILENO) {
		CUSTOMER_MOBILENO = cUSTOMER_MOBILENO;
	}
	public String getCUSTOMER_ALTERNATE_NO() {
		return CUSTOMER_ALTERNATE_NO;
	}
	public void setCUSTOMER_ALTERNATE_NO(String cUSTOMER_ALTERNATE_NO) {
		CUSTOMER_ALTERNATE_NO = cUSTOMER_ALTERNATE_NO;
	}
	public String getEND_PERSON_CUSTOMER_NAME() {
		return END_PERSON_CUSTOMER_NAME;
	}
	public void setEND_PERSON_CUSTOMER_NAME(String eND_PERSON_CUSTOMER_NAME) {
		END_PERSON_CUSTOMER_NAME = eND_PERSON_CUSTOMER_NAME;
	}
	public String getEND_PERSON_CUSTOMER_CONTACTNO() {
		return END_PERSON_CUSTOMER_CONTACTNO;
	}
	public void setEND_PERSON_CUSTOMER_CONTACTNO(
			String eND_PERSON_CUSTOMER_CONTACTNO) {
		END_PERSON_CUSTOMER_CONTACTNO = eND_PERSON_CUSTOMER_CONTACTNO;
	}
	public String getPMC_NAME() {
		return PMC_NAME;
	}
	public void setPMC_NAME(String pMC_NAME) {
		PMC_NAME = pMC_NAME;
	}
	public String getPMC_CONTACT_PERSON() {
		return PMC_CONTACT_PERSON;
	}
	public void setPMC_CONTACT_PERSON(String pMC_CONTACT_PERSON) {
		PMC_CONTACT_PERSON = pMC_CONTACT_PERSON;
	}
	public String getPMC_CONTACT_NO() {
		return PMC_CONTACT_NO;
	}
	public void setPMC_CONTACT_NO(String pMC_CONTACT_NO) {
		PMC_CONTACT_NO = pMC_CONTACT_NO;
	}
	public String getPMC_CONTACT_ALT_NO() {
		return PMC_CONTACT_ALT_NO;
	}
	public void setPMC_CONTACT_ALT_NO(String pMC_CONTACT_ALT_NO) {
		PMC_CONTACT_ALT_NO = pMC_CONTACT_ALT_NO;
	}
	public String getLOW_SIDE_SUPPLY_BASIC() {
		return LOW_SIDE_SUPPLY_BASIC;
	}
	public void setLOW_SIDE_SUPPLY_BASIC(String lOW_SIDE_SUPPLY_BASIC) {
		LOW_SIDE_SUPPLY_BASIC = lOW_SIDE_SUPPLY_BASIC;
	}
	public String getLOW_SIDE_LABOUR_BASIC() {
		return LOW_SIDE_LABOUR_BASIC;
	}
	public void setLOW_SIDE_LABOUR_BASIC(String lOW_SIDE_LABOUR_BASIC) {
		LOW_SIDE_LABOUR_BASIC = lOW_SIDE_LABOUR_BASIC;
	}
	public String getLOW_SIDE_MARGIN() {
		return LOW_SIDE_MARGIN;
	}
	public void setLOW_SIDE_MARGIN(String lOW_SIDE_MARGIN) {
		LOW_SIDE_MARGIN = lOW_SIDE_MARGIN;
	}
	public String getPROJECT_MARGIN() {
		return PROJECT_MARGIN;
	}
	public void setPROJECT_MARGIN(String pROJECT_MARGIN) {
		PROJECT_MARGIN = pROJECT_MARGIN;
	}
	public String getDG_ED_VALUE() {
		return DG_ED_VALUE;
	}
	public void setDG_ED_VALUE(String dG_ED_VALUE) {
		DG_ED_VALUE = dG_ED_VALUE;
	}
	public String getPROJECT_TOTAL() {
		return PROJECT_TOTAL;
	}
	public void setPROJECT_TOTAL(String pROJECT_TOTAL) {
		PROJECT_TOTAL = pROJECT_TOTAL;
	}
	public String getDTL_RATING() {
		return DTL_RATING;
	}
	public void setDTL_RATING(String dTL_RATING) {
		DTL_RATING = dTL_RATING;
	}
	public String getDTL_ITEM_TYPE() {
		return DTL_ITEM_TYPE;
	}
	public void setDTL_ITEM_TYPE(String dTL_ITEM_TYPE) {
		DTL_ITEM_TYPE = dTL_ITEM_TYPE;
	}
	public String getDTL_ENGINE_MAKE() {
		return DTL_ENGINE_MAKE;
	}
	public void setDTL_ENGINE_MAKE(String dTL_ENGINE_MAKE) {
		DTL_ENGINE_MAKE = dTL_ENGINE_MAKE;
	}
	public String getDTL_ENGINE_MODEL() {
		return DTL_ENGINE_MODEL;
	}
	public void setDTL_ENGINE_MODEL(String dTL_ENGINE_MODEL) {
		DTL_ENGINE_MODEL = dTL_ENGINE_MODEL;
	}
	public String getDTL_ALTERNATOR_MAKE() {
		return DTL_ALTERNATOR_MAKE;
	}
	public void setDTL_ALTERNATOR_MAKE(String dTL_ALTERNATOR_MAKE) {
		DTL_ALTERNATOR_MAKE = dTL_ALTERNATOR_MAKE;
	}
	public String getDTL_ALTERNATOR_MODEL() {
		return DTL_ALTERNATOR_MODEL;
	}
	public void setDTL_ALTERNATOR_MODEL(String dTL_ALTERNATOR_MODEL) {
		DTL_ALTERNATOR_MODEL = dTL_ALTERNATOR_MODEL;
	}
	public String getDTL_VOLTAGE() {
		return DTL_VOLTAGE;
	}
	public void setDTL_VOLTAGE(String dTL_VOLTAGE) {
		DTL_VOLTAGE = dTL_VOLTAGE;
	}
	public String getDTL_HZ() {
		return DTL_HZ;
	}
	public void setDTL_HZ(String dTL_HZ) {
		DTL_HZ = dTL_HZ;
	}
	public String getDTL_QTY() {
		return DTL_QTY;
	}
	public void setDTL_QTY(String dTL_QTY) {
		DTL_QTY = dTL_QTY;
	}
	public String getDTL_COOLING_SYSTEM() {
		return DTL_COOLING_SYSTEM;
	}
	public void setDTL_COOLING_SYSTEM(String dTL_COOLING_SYSTEM) {
		DTL_COOLING_SYSTEM = dTL_COOLING_SYSTEM;
	}
	public String getDTL_AMOUNT() {
		return DTL_AMOUNT;
	}
	public void setDTL_AMOUNT(String dTL_AMOUNT) {
		DTL_AMOUNT = dTL_AMOUNT;
	}
	public String getDTL_FLEX1() {
		return DTL_FLEX1;
	}
	public void setDTL_FLEX1(String dTL_FLEX1) {
		DTL_FLEX1 = dTL_FLEX1;
	}
	public String getPROJECT_REFERENCE() {
		return PROJECT_REFERENCE;
	}
	public void setPROJECT_REFERENCE(String pROJECT_REFERENCE) {
		PROJECT_REFERENCE = pROJECT_REFERENCE;
	}
	
	
	
}
